import uuid
import logging
from typing import Dict, Any, Optional, Union
from hsci.core.data_types import (
    PlanningFailure, VerificationResult, VerificationStatus, Precondition,
    ReflectionFailureType, ReflectionResult
)

logger = logging.getLogger("HSCI.Reasoning.ReflectionEngine")


class ReflectionEngine:
    """
    LAYER 4B: Reflection & Failure Diagnosis Engine
    Translates cognitive failure evidence (HTN PlanningFailure or final VerificationResult)
    into a deterministic, typed ReflectionResult artifact for WorkingMemory and future learning.
    Does NOT mutate methods, rules, or neural weights.
    """

    def reflect_planning_failure(
        self,
        failure: PlanningFailure,
        request_id: str = ""
    ) -> ReflectionResult:
        """
        Diagnoses an HTN PlanningFailure payload generated by HTNPlanner.
        """
        ref_id = f"ref-{uuid.uuid4().hex[:8]}"
        reason_lower = failure.reason.lower()

        # Determine typed failure category from structured failure payload
        if "max decomposition depth" in reason_lower:
            cat = ReflectionFailureType.MAX_DEPTH_EXCEEDED
            root_cause = f"Task decomposition exceeded maximum depth limit ({failure.depth_reached}). Possible recursion leak."
            hint = "Increase domain method specialization or verify task hierarchy termination."
            retry = False
        elif "cycle detected" in reason_lower:
            cat = ReflectionFailureType.DECOMPOSITION_CYCLE
            root_cause = f"Cycle detected along active decomposition branch for task '{failure.failed_task_name}'."
            hint = "Ensure HTN methods do not recursively invoke ancestor tasks in the same branch."
            retry = False
        elif "no decomposition method" in reason_lower:
            cat = ReflectionFailureType.NO_METHOD
            root_cause = f"No method registered to decompose compound task '{failure.failed_task_name}'."
            hint = "Register a valid Method definition for this compound task in MethodRegistry."
            retry = False
        elif "unsat" in reason_lower or failure.failed_precondition is not None or "precondition" in reason_lower:
            cat = ReflectionFailureType.PRECONDITION_UNSAT
            pre_name = failure.failed_precondition.predicate if failure.failed_precondition else "UNKNOWN"
            root_cause = f"Precondition '{pre_name}' unsatisfiable under current planning context state."
            hint = f"Ensure required state for precondition '{pre_name}' is available in WorkingMemory facts."
            retry = True  # State update might allow retry
        else:
            cat = ReflectionFailureType.STRUCTURAL_DECOMPOSITION_FAILURE
            root_cause = f"All candidate methods failed structural reduction for task '{failure.failed_task_name}'."
            hint = "Check child subtask registration and preconditions."
            retry = False

        result = ReflectionResult(
            reflection_id=ref_id,
            request_id=request_id,
            failure_category=cat,
            failed_stage="PLANNING",
            failed_task_id=failure.failed_task_id,
            failed_task_name=failure.failed_task_name,
            attempted_methods=list(failure.attempted_methods),
            failed_precondition=failure.failed_precondition,
            counterexample=failure.z3_counterexample,
            depth_reached=failure.depth_reached,
            root_cause=root_cause,
            correction_hint=hint,
            retry_recommended=retry
        )
        logger.info(f"Reflected planning failure '{cat.value}' on task '{failure.failed_task_name}'")
        return result

    def reflect_verification_failure(
        self,
        verification: VerificationResult,
        request_id: str = "",
        task_name: str = "FINAL_SOLUTION"
    ) -> ReflectionResult:
        """
        Diagnoses a candidate solution VerificationResult rejection from Z3VerificationEngine.
        """
        ref_id = f"ref-{uuid.uuid4().hex[:8]}"

        if verification.status == VerificationStatus.TIMEOUT:
            cat = ReflectionFailureType.SOLVER_TIMEOUT
            root_cause = "Z3 SMT solver execution timed out before proving or disproving candidate."
            hint = "Check constraint complexity or increase z3_timeout_ms config."
            retry = True
        elif verification.status == VerificationStatus.DISPROVEN:
            cat = ReflectionFailureType.SOLUTION_VERIFICATION_FAILURE
            root_cause = "Candidate solution contradicts known mathematical or domain constraints."
            hint = verification.correction_hint or "Adjust concept selection or candidate equation synthesis."
            retry = True
        else:
            cat = ReflectionFailureType.SOLVER_UNSAT
            root_cause = "Solver was unable to satisfy proposed candidate solution constraints."
            hint = "Verify entity input values and mathematical operators."
            retry = True

        result = ReflectionResult(
            reflection_id=ref_id,
            request_id=request_id,
            failure_category=cat,
            failed_stage="SOLUTION_VERIFICATION",
            failed_task_id="",
            failed_task_name=task_name,
            attempted_methods=[],
            failed_precondition=None,
            counterexample=verification.counterexample,
            depth_reached=0,
            root_cause=root_cause,
            correction_hint=verification.correction_hint or hint,
            retry_recommended=retry
        )
        logger.info(f"Reflected verification failure '{cat.value}' for '{task_name}'")
        return result
